version: '3'
services:
  # nginx server for proxy
  nginx:
    image: 'mattivdweem/pizza-party-nginx:latest'
    depends_on:
      - api
      - platform
    build:
      context: ./nginx
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/snippets:/etc/nginx/snippets'
      - './nginx/certs:/etc/ssl/certs'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    environment:
      NODE_ENV: production
    networks:
      - pizza-network

  # node.js service for api
  platform:
    image: 'mattivdweem/pizza-party-platform:latest'
    build:
      context: ./platform
    volumes:
      - './platform:/usr/src/app'
    environment:
      NODE_ENV: production
    networks:
      - pizza-network

  # next.js service for react front-end
  api:
    image: 'mattivdweem/pizza-party-api:latest'
    build:
      context: ./api
    depends_on:
      - db
    volumes:
      - './api:/usr/src/app'
      - './api/config:/usr/src/app/config'
      - './api/node_modules/:/usr/src/app/node_modules/'
      - 'data-backend-volume:/var/lib/postgresql/data'
    environment:
      NODE_ENV: production
      PORT: "7002"
    networks:
      - pizza-network
      - data-backend-network
      
  db:
    image: postgres
    ports:
      - "54320:5432"
    networks:
      - data-backend-network
    environment:
      POSTGRES_DB: "pizza-party-database"



# pre-defined networking
networks:
  # the nginx network for proxy
  pizza-network:
    driver: bridge
  # the databackend, to access databases
  data-backend-network:
    driver: bridge

# generated volumes
volumes:
  data-backend-volume:

